name: Build Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04 # একটি নির্দিষ্ট স্ট্যাবল লিনাক্স এনভায়রনমেন্ট সেট করা হলো
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Build Android APK with Buildozer
        uses: ArtemGovorov/buildozer-action@v1
        with:
          workdir: .
          # এরর এড়াতে কিভি মাস্টারের সাথে এটি অটোমেটিক ব্যাকগ্রাউন্ড সেটআপ করে নেবে

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GuessingGame-APK
          path: bin/*.apk
