name: Build Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Build Android APK with Buildozer
        uses: ArtemGovorov/buildozer-action@v1

        with:
          workdir: .

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GuessingGame-APK
          path: bin/*.apk
